### ISSUE TITLE
Remove _ssl module requirement

### ISSUE THREAD

**Issue by lmcapser** [cs01/gdbgui#170]
##### Describe the issue
While SSL support is most definitely useful and appreciated, would it be possible to remove the requirement for the ssl module if the feature is not enabled?

##### Steps to replicate

* When running in a custom cross-compiler environment, our python distribution does not support SSL.  Unfortunately, this prevents using gdbgui later than v0.9.4 as it fails for "ImportError: No module named _ssl" despite the fact we don't need it in this particular environment.

##### Describe your environment
* CentOS-7 based custom linux distro
* gdbgui version (`gdbgui -v`): 0.11.0.0
* gdb version (`gdb -v`): 7.12.1
* browser:Google Chrome Version 61.0.3163.100
* python packages (`pip freeze`):
click-6.7
enum34-1.1.6
enum-compat-0.0.2
eventlet-0.21.0
Flask-0.12.2
Flask-Compress-1.4.0
Flask-SocketIO-2.9.3
gdbgui-0.11.0.0
gevent-1.2.2
greenlet-0.4.12
itsdangerous-0.24
pygdbmi-0.8.2.0
Pygments-2.2.0
pypugjs-4.2.2
python-engineio-2.0.1
python-socketio-1.8.4
six-1.11.0
Werkzeug-0.13

**Comment by cs01** [comment]
Thanks, that sounds reasonable. Would this fix your issue? In other words, is the Exception being raised an `ImportError`?

```
try:
    from gdbgui.SSLify import SSLify, get_ssl_context  # noqa
except ImportError:
    print('Warning: Optional SSL support is not available')
```

**Comment by lmcapser** [comment]
Yes, that's exactly what I had in mind!

**Comment by cs01** [comment]
👍 I will add it to the next update

**Comment by lmcapser** [comment]
Here's the Stack Trace:
Traceback (most recent call last):
  File "/opt/tools/sig_python-2.7.13/bin/gdbgui", line 9, in <module>
    load_entry_point('gdbgui==0.11.0.0', 'console_scripts', 'gdbgui')()
  File "/opt/tools/sig_python-2.7.13/lib/python2.7/site-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/tools/sig_python-2.7.13/lib/python2.7/site-packages/pkg_resources.py", line 2311, in load_entry_point
    return ep.load()
  File "/opt/tools/sig_python-2.7.13/lib/python2.7/site-packages/pkg_resources.py", line 2017, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/opt/tools/sig_python-2.7.13/lib/python2.7/site-packages/gdbgui-0.11.0.0-py2.7.egg/gdbgui/backend.py", line 37, in <module>
    from gdbgui.SSLify import SSLify, get_ssl_context  # noqa
  File "/opt/tools/sig_python-2.7.13/lib/python2.7/site-packages/gdbgui-0.11.0.0-py2.7.egg/gdbgui/SSLify.py", line 6, in <module>
    import ssl
  File "/opt/tools/sig_python-2.7.13/lib/python2.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl

**Comment by lmcapser** [comment]
Thanks!!

**Comment by cs01** [comment]
this has been fixed in v0.11.1.1

**Comment by lmcapser** [comment]
Chad,

Is it possible something was missed?  I installed the update and, while I
get the message about the availability of SSL support, I'm still seeing an
error:

*Warning: Optional SSL support is not available*
*Traceback (most recent call last):*
*  File "/opt/sigsw/el7/tools/sig_python-2.7.13/bin/gdbgui", line 9, in
<module>*
*    load_entry_point('gdbgui==0.11.1.1', 'console_scripts', 'gdbgui')()*
*  File
"/opt/sigsw/el7/tools/sig_python-2.7.13/lib/python2.7/site-packages/gdbgui-0.11.1.1-py2.7.egg/gdbgui/backend.py",
line 718, in main*
*    LLDB=(args.lldb or 'lldb-mi' in args.gdb.lower()))*
*  File
"/opt/sigsw/el7/tools/sig_python-2.7.13/lib/python2.7/site-packages/gdbgui-0.11.1.1-py2.7.egg/gdbgui/backend.py",
line 147, in setup_backend*
*    ssl_context = get_ssl_context(private_key, certificate)*
*NameError: global name 'get_ssl_context' is not defined*

Thanks,
Lance

**Comment by cs01** [comment]
Yup definitely didn't fully implement that.  Will fix in a new release, sorry about that.

**Comment by cs01** [comment]
ok should be fixed in 0.11.1.2

**Comment by lmcapser** [comment]
Chad,

Just a quick update to let you know the changes worked and I can run gdbgui
w/o the SSL module installed.

Thank you for the quick response!
Lance
